-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity TOP_TOP_Pipeline_VITIS_LOOP_49_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    empty : IN STD_LOGIC_VECTOR (7 downto 0);
    ia_assign : IN STD_LOGIC_VECTOR (31 downto 0);
    ans_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    ans_0_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of TOP_TOP_Pipeline_VITIS_LOOP_49_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv26_2010103 : STD_LOGIC_VECTOR (25 downto 0) := "10000000010000000100000011";
    constant ap_const_lv26_1030201 : STD_LOGIC_VECTOR (25 downto 0) := "01000000110000001000000001";
    constant ap_const_lv26_3020101 : STD_LOGIC_VECTOR (25 downto 0) := "11000000100000000100000001";
    constant ap_const_lv26_1010302 : STD_LOGIC_VECTOR (25 downto 0) := "01000000010000001100000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_1B : STD_LOGIC_VECTOR (7 downto 0) := "00011011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln49_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal j_fu_100 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal j_4_fu_146_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal pans_fu_104 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pans_2_fu_559_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ib_fu_159_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal ib_fu_159_p9 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln60_fu_179_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln68_fu_190_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal a_fu_193_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_201_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_20_fu_208_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_222_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_21_fu_214_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_247_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_34_fu_238_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_263_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal a_23_fu_272_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_280_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_24_fu_287_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln4_fu_301_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln65_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_25_fu_293_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_16_fu_334_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_35_fu_325_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_350_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal a_27_fu_359_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_17_fu_367_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_28_fu_374_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln71_3_fu_388_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln65_2_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_29_fu_380_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_fu_421_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_36_fu_412_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_437_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal a_31_fu_446_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_fu_454_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_32_fu_461_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_fu_475_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_33_fu_467_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln65_fu_230_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln65_12_fu_483_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln65_8_fu_317_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_fu_183_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln74_fu_491_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln74_7_fu_497_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_11_fu_342_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_9_fu_255_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln65_10_fu_404_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln74_10_fu_509_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln74_9_fu_515_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_13_fu_429_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln74_11_fu_521_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln74_8_fu_503_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal oans_fu_527_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln76_fu_537_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_ln1_fu_541_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln76_fu_533_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln76_2_fu_549_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln76_fu_553_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ib_fu_159_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ib_fu_159_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ib_fu_159_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component TOP_sparsemux_7_32_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (31 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (31 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (31 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (25 downto 0);
        din1 : IN STD_LOGIC_VECTOR (25 downto 0);
        din2 : IN STD_LOGIC_VECTOR (25 downto 0);
        def : IN STD_LOGIC_VECTOR (25 downto 0);
        sel : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component TOP_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_7_32_26_1_1_U7 : component TOP_sparsemux_7_32_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000000000000000000000000000011",
        din0_WIDTH => 26,
        CASE1 => "00000000000000000000000000000001",
        din1_WIDTH => 26,
        CASE2 => "00000000000000000000000000000010",
        din2_WIDTH => 26,
        def_WIDTH => 26,
        sel_WIDTH => 32,
        dout_WIDTH => 26)
    port map (
        din0 => ap_const_lv26_2010103,
        din1 => ap_const_lv26_1030201,
        din2 => ap_const_lv26_3020101,
        def => ap_const_lv26_1010302,
        sel => ib_fu_159_p8,
        dout => ib_fu_159_p9);

    flow_control_loop_pipe_sequential_init_U : component TOP_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    j_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_100 <= ap_const_lv3_0;
                elsif (((icmp_ln49_fu_140_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    j_fu_100 <= j_4_fu_146_p2;
                end if;
            end if; 
        end if;
    end process;

    pans_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    pans_fu_104 <= ap_const_lv32_0;
                elsif (((icmp_ln49_fu_140_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    pans_fu_104 <= pans_2_fu_559_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_20_fu_208_p2 <= (ap_const_lv8_1B xor a_fu_193_p3);
    a_21_fu_214_p3 <= 
        a_20_fu_208_p2 when (tmp_12_fu_201_p3(0) = '1') else 
        a_fu_193_p3;
    a_23_fu_272_p3 <= (tmp_s_fu_263_p4 & ap_const_lv1_0);
    a_24_fu_287_p2 <= (ap_const_lv8_1B xor a_23_fu_272_p3);
    a_25_fu_293_p3 <= 
        a_24_fu_287_p2 when (tmp_15_fu_280_p3(0) = '1') else 
        a_23_fu_272_p3;
    a_27_fu_359_p3 <= (tmp_1_fu_350_p4 & ap_const_lv1_0);
    a_28_fu_374_p2 <= (ap_const_lv8_1B xor a_27_fu_359_p3);
    a_29_fu_380_p3 <= 
        a_28_fu_374_p2 when (tmp_17_fu_367_p3(0) = '1') else 
        a_27_fu_359_p3;
    a_31_fu_446_p3 <= (tmp_2_fu_437_p4 & ap_const_lv1_0);
    a_32_fu_461_p2 <= (ap_const_lv8_1B xor a_31_fu_446_p3);
    a_33_fu_467_p3 <= 
        a_32_fu_461_p2 when (tmp_19_fu_454_p3(0) = '1') else 
        a_31_fu_446_p3;
    a_34_fu_238_p4 <= ia_assign(15 downto 8);
    a_35_fu_325_p4 <= ia_assign(23 downto 16);
    a_36_fu_412_p4 <= ia_assign(31 downto 24);
    a_fu_193_p3 <= (trunc_ln68_fu_190_p1 & ap_const_lv1_0);
    ans_0_out <= pans_fu_104;

    ans_0_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln49_fu_140_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln49_fu_140_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ans_0_out_ap_vld <= ap_const_logic_1;
        else 
            ans_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln49_fu_140_p2)
    begin
        if (((icmp_ln49_fu_140_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    b_fu_421_p3 <= ib_fu_159_p9(24 downto 24);
    ib_fu_159_p8 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_fu_100),32));
    icmp_ln49_fu_140_p2 <= "1" when (j_fu_100 = ap_const_lv3_4) else "0";
    icmp_ln65_2_fu_398_p2 <= "0" when (trunc_ln71_3_fu_388_p4 = ap_const_lv7_0) else "1";
    icmp_ln65_fu_311_p2 <= "0" when (trunc_ln4_fu_301_p4 = ap_const_lv7_0) else "1";
    j_4_fu_146_p2 <= std_logic_vector(unsigned(j_fu_100) + unsigned(ap_const_lv3_1));
    oans_fu_527_p2 <= (xor_ln74_8_fu_503_p2 xor xor_ln74_11_fu_521_p2);
    p_11_fu_342_p3 <= 
        a_35_fu_325_p4 when (tmp_16_fu_334_p3(0) = '1') else 
        ap_const_lv8_0;
    p_13_fu_429_p3 <= 
        a_36_fu_412_p4 when (b_fu_421_p3(0) = '1') else 
        ap_const_lv8_0;
    p_9_fu_255_p3 <= 
        a_34_fu_238_p4 when (tmp_14_fu_247_p3(0) = '1') else 
        ap_const_lv8_0;
    p_fu_183_p3 <= 
        empty when (trunc_ln60_fu_179_p1(0) = '1') else 
        ap_const_lv8_0;
    pans_2_fu_559_p2 <= (shl_ln76_fu_553_p2 or pans_fu_104);
    select_ln65_10_fu_404_p3 <= 
        a_29_fu_380_p3 when (icmp_ln65_2_fu_398_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln65_12_fu_483_p3 <= 
        a_33_fu_467_p3 when (tmp_20_fu_475_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln65_8_fu_317_p3 <= 
        a_25_fu_293_p3 when (icmp_ln65_fu_311_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln65_fu_230_p3 <= 
        a_21_fu_214_p3 when (tmp_13_fu_222_p3(0) = '1') else 
        ap_const_lv8_0;
    shl_ln1_fu_541_p3 <= (trunc_ln76_fu_537_p1 & ap_const_lv3_0);
    shl_ln76_fu_553_p2 <= std_logic_vector(shift_left(unsigned(zext_ln76_fu_533_p1),to_integer(unsigned('0' & zext_ln76_2_fu_549_p1(31-1 downto 0)))));
    tmp_12_fu_201_p3 <= empty(7 downto 7);
    tmp_13_fu_222_p3 <= ib_fu_159_p9(1 downto 1);
    tmp_14_fu_247_p3 <= ib_fu_159_p9(8 downto 8);
    tmp_15_fu_280_p3 <= ia_assign(15 downto 15);
    tmp_16_fu_334_p3 <= ib_fu_159_p9(16 downto 16);
    tmp_17_fu_367_p3 <= ia_assign(23 downto 23);
    tmp_19_fu_454_p3 <= ia_assign(31 downto 31);
    tmp_1_fu_350_p4 <= ia_assign(22 downto 16);
    tmp_20_fu_475_p3 <= ib_fu_159_p9(25 downto 25);
    tmp_2_fu_437_p4 <= ia_assign(30 downto 24);
    tmp_s_fu_263_p4 <= ia_assign(14 downto 8);
    trunc_ln4_fu_301_p4 <= ib_fu_159_p9(15 downto 9);
    trunc_ln60_fu_179_p1 <= ib_fu_159_p9(1 - 1 downto 0);
    trunc_ln68_fu_190_p1 <= ia_assign(7 - 1 downto 0);
    trunc_ln71_3_fu_388_p4 <= ib_fu_159_p9(23 downto 17);
    trunc_ln76_fu_537_p1 <= j_fu_100(2 - 1 downto 0);
    xor_ln74_10_fu_509_p2 <= (p_9_fu_255_p3 xor p_11_fu_342_p3);
    xor_ln74_11_fu_521_p2 <= (xor_ln74_9_fu_515_p2 xor p_13_fu_429_p3);
    xor_ln74_7_fu_497_p2 <= (select_ln65_8_fu_317_p3 xor p_fu_183_p3);
    xor_ln74_8_fu_503_p2 <= (xor_ln74_fu_491_p2 xor xor_ln74_7_fu_497_p2);
    xor_ln74_9_fu_515_p2 <= (xor_ln74_10_fu_509_p2 xor select_ln65_10_fu_404_p3);
    xor_ln74_fu_491_p2 <= (select_ln65_fu_230_p3 xor select_ln65_12_fu_483_p3);
    zext_ln76_2_fu_549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_541_p3),32));
    zext_ln76_fu_533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oans_fu_527_p2),32));
end behav;
