-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity TOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    IN_r_TDATA : IN STD_LOGIC_VECTOR (191 downto 0);
    IN_r_TVALID : IN STD_LOGIC;
    IN_r_TREADY : OUT STD_LOGIC;
    OUT_r_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    OUT_r_TVALID : OUT STD_LOGIC;
    OUT_r_TREADY : IN STD_LOGIC );
end;


architecture behav of TOP is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "TOP_TOP,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.085000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=614,HLS_SYN_LUT=1043,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_TOP_Pipeline_1_fu_122_ap_start : STD_LOGIC;
    signal grp_TOP_Pipeline_1_fu_122_ap_done : STD_LOGIC;
    signal grp_TOP_Pipeline_1_fu_122_ap_idle : STD_LOGIC;
    signal grp_TOP_Pipeline_1_fu_122_ap_ready : STD_LOGIC;
    signal grp_TOP_Pipeline_1_fu_122_inreg_0_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_TOP_Pipeline_1_fu_122_inreg_0_1_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_1_fu_122_inreg_1_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_TOP_Pipeline_1_fu_122_inreg_1_1_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_1_fu_122_inreg_0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_TOP_Pipeline_1_fu_122_inreg_0_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_1_fu_122_inreg_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_TOP_Pipeline_1_fu_122_inreg_1_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_ap_start : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_ap_done : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_ap_idle : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_ap_ready : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_0 : STD_LOGIC_VECTOR (57 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_7 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_7_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_7 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_7_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_6 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_6_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_6 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_6_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_5 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_5_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_5 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_5_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_4 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_4_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_4 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_4_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_3_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_3_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_2_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_2_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_0_1_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_1_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_2_fu_130_outreg_1 : STD_LOGIC_VECTOR (57 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_outreg_1_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_start : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_done : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_idle : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_ready : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_OUT_r_TREADY : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_IN_r_TREADY : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_OUT_r_TDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_OUT_r_TVALID : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_1_o : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_1_o_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_o : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_o_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_o : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_o_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_1_o : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_1_o_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_0_o : STD_LOGIC_VECTOR (57 downto 0);
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_0_o_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_1_o : STD_LOGIC_VECTOR (57 downto 0);
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_1_o_ap_vld : STD_LOGIC;
    signal grp_TOP_Pipeline_1_fu_122_ap_start_reg : STD_LOGIC := '0';
    signal inreg_0_1_fu_50 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal inreg_1_1_fu_54 : STD_LOGIC_VECTOR (63 downto 0);
    signal inreg_0_fu_42 : STD_LOGIC_VECTOR (63 downto 0);
    signal inreg_1_fu_46 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_TOP_Pipeline_2_fu_130_ap_start_reg : STD_LOGIC := '0';
    signal outreg_0_fu_58 : STD_LOGIC_VECTOR (57 downto 0);
    signal outreg_0_7_fu_114 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_1_7_fu_118 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_0_6_fu_106 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_1_6_fu_110 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_0_5_fu_98 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_1_5_fu_102 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_0_4_fu_90 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_1_4_fu_94 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_0_3_fu_82 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_1_3_fu_86 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_0_2_fu_74 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_1_2_fu_78 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_0_1_fu_66 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_1_1_fu_70 : STD_LOGIC_VECTOR (0 downto 0);
    signal outreg_1_fu_62 : STD_LOGIC_VECTOR (57 downto 0);
    signal grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal regslice_both_OUT_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal regslice_both_IN_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal IN_r_TDATA_int_regslice : STD_LOGIC_VECTOR (191 downto 0);
    signal IN_r_TVALID_int_regslice : STD_LOGIC;
    signal IN_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_IN_r_V_data_V_U_ack_in : STD_LOGIC;
    signal OUT_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_OUT_r_V_data_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component TOP_TOP_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inreg_0_1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        inreg_0_1_ap_vld : OUT STD_LOGIC;
        inreg_1_1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        inreg_1_1_ap_vld : OUT STD_LOGIC;
        inreg_0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        inreg_0_ap_vld : OUT STD_LOGIC;
        inreg_1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        inreg_1_ap_vld : OUT STD_LOGIC );
    end component;


    component TOP_TOP_Pipeline_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        outreg_0 : OUT STD_LOGIC_VECTOR (57 downto 0);
        outreg_0_ap_vld : OUT STD_LOGIC;
        outreg_0_7 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_7_ap_vld : OUT STD_LOGIC;
        outreg_1_7 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_7_ap_vld : OUT STD_LOGIC;
        outreg_0_6 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_6_ap_vld : OUT STD_LOGIC;
        outreg_1_6 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_6_ap_vld : OUT STD_LOGIC;
        outreg_0_5 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_5_ap_vld : OUT STD_LOGIC;
        outreg_1_5 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_5_ap_vld : OUT STD_LOGIC;
        outreg_0_4 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_4_ap_vld : OUT STD_LOGIC;
        outreg_1_4 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_4_ap_vld : OUT STD_LOGIC;
        outreg_0_3 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_3_ap_vld : OUT STD_LOGIC;
        outreg_1_3 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_3_ap_vld : OUT STD_LOGIC;
        outreg_0_2 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_2_ap_vld : OUT STD_LOGIC;
        outreg_1_2 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_2_ap_vld : OUT STD_LOGIC;
        outreg_0_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_1_ap_vld : OUT STD_LOGIC;
        outreg_1_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_1_ap_vld : OUT STD_LOGIC;
        outreg_1 : OUT STD_LOGIC_VECTOR (57 downto 0);
        outreg_1_ap_vld : OUT STD_LOGIC );
    end component;


    component TOP_TOP_Pipeline_VITIS_LOOP_177_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        IN_r_TVALID : IN STD_LOGIC;
        OUT_r_TREADY : IN STD_LOGIC;
        IN_r_TDATA : IN STD_LOGIC_VECTOR (191 downto 0);
        IN_r_TREADY : OUT STD_LOGIC;
        OUT_r_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        OUT_r_TVALID : OUT STD_LOGIC;
        inreg_0_1_i : IN STD_LOGIC_VECTOR (63 downto 0);
        inreg_0_1_o : OUT STD_LOGIC_VECTOR (63 downto 0);
        inreg_0_1_o_ap_vld : OUT STD_LOGIC;
        inreg_0_i : IN STD_LOGIC_VECTOR (63 downto 0);
        inreg_0_o : OUT STD_LOGIC_VECTOR (63 downto 0);
        inreg_0_o_ap_vld : OUT STD_LOGIC;
        inreg_1_i : IN STD_LOGIC_VECTOR (63 downto 0);
        inreg_1_o : OUT STD_LOGIC_VECTOR (63 downto 0);
        inreg_1_o_ap_vld : OUT STD_LOGIC;
        inreg_1_1_i : IN STD_LOGIC_VECTOR (63 downto 0);
        inreg_1_1_o : OUT STD_LOGIC_VECTOR (63 downto 0);
        inreg_1_1_o_ap_vld : OUT STD_LOGIC;
        outreg_0_i : IN STD_LOGIC_VECTOR (57 downto 0);
        outreg_0_o : OUT STD_LOGIC_VECTOR (57 downto 0);
        outreg_0_o_ap_vld : OUT STD_LOGIC;
        outreg_1_i : IN STD_LOGIC_VECTOR (57 downto 0);
        outreg_1_o : OUT STD_LOGIC_VECTOR (57 downto 0);
        outreg_1_o_ap_vld : OUT STD_LOGIC;
        outreg_0_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_3 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_3 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_4 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_4 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_5 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_5 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_6 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_6 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_0_7 : IN STD_LOGIC_VECTOR (0 downto 0);
        outreg_1_7 : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component TOP_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_TOP_Pipeline_1_fu_122 : component TOP_TOP_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_TOP_Pipeline_1_fu_122_ap_start,
        ap_done => grp_TOP_Pipeline_1_fu_122_ap_done,
        ap_idle => grp_TOP_Pipeline_1_fu_122_ap_idle,
        ap_ready => grp_TOP_Pipeline_1_fu_122_ap_ready,
        inreg_0_1 => grp_TOP_Pipeline_1_fu_122_inreg_0_1,
        inreg_0_1_ap_vld => grp_TOP_Pipeline_1_fu_122_inreg_0_1_ap_vld,
        inreg_1_1 => grp_TOP_Pipeline_1_fu_122_inreg_1_1,
        inreg_1_1_ap_vld => grp_TOP_Pipeline_1_fu_122_inreg_1_1_ap_vld,
        inreg_0 => grp_TOP_Pipeline_1_fu_122_inreg_0,
        inreg_0_ap_vld => grp_TOP_Pipeline_1_fu_122_inreg_0_ap_vld,
        inreg_1 => grp_TOP_Pipeline_1_fu_122_inreg_1,
        inreg_1_ap_vld => grp_TOP_Pipeline_1_fu_122_inreg_1_ap_vld);

    grp_TOP_Pipeline_2_fu_130 : component TOP_TOP_Pipeline_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_TOP_Pipeline_2_fu_130_ap_start,
        ap_done => grp_TOP_Pipeline_2_fu_130_ap_done,
        ap_idle => grp_TOP_Pipeline_2_fu_130_ap_idle,
        ap_ready => grp_TOP_Pipeline_2_fu_130_ap_ready,
        outreg_0 => grp_TOP_Pipeline_2_fu_130_outreg_0,
        outreg_0_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_0_ap_vld,
        outreg_0_7 => grp_TOP_Pipeline_2_fu_130_outreg_0_7,
        outreg_0_7_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_0_7_ap_vld,
        outreg_1_7 => grp_TOP_Pipeline_2_fu_130_outreg_1_7,
        outreg_1_7_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_1_7_ap_vld,
        outreg_0_6 => grp_TOP_Pipeline_2_fu_130_outreg_0_6,
        outreg_0_6_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_0_6_ap_vld,
        outreg_1_6 => grp_TOP_Pipeline_2_fu_130_outreg_1_6,
        outreg_1_6_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_1_6_ap_vld,
        outreg_0_5 => grp_TOP_Pipeline_2_fu_130_outreg_0_5,
        outreg_0_5_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_0_5_ap_vld,
        outreg_1_5 => grp_TOP_Pipeline_2_fu_130_outreg_1_5,
        outreg_1_5_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_1_5_ap_vld,
        outreg_0_4 => grp_TOP_Pipeline_2_fu_130_outreg_0_4,
        outreg_0_4_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_0_4_ap_vld,
        outreg_1_4 => grp_TOP_Pipeline_2_fu_130_outreg_1_4,
        outreg_1_4_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_1_4_ap_vld,
        outreg_0_3 => grp_TOP_Pipeline_2_fu_130_outreg_0_3,
        outreg_0_3_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_0_3_ap_vld,
        outreg_1_3 => grp_TOP_Pipeline_2_fu_130_outreg_1_3,
        outreg_1_3_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_1_3_ap_vld,
        outreg_0_2 => grp_TOP_Pipeline_2_fu_130_outreg_0_2,
        outreg_0_2_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_0_2_ap_vld,
        outreg_1_2 => grp_TOP_Pipeline_2_fu_130_outreg_1_2,
        outreg_1_2_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_1_2_ap_vld,
        outreg_0_1 => grp_TOP_Pipeline_2_fu_130_outreg_0_1,
        outreg_0_1_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_0_1_ap_vld,
        outreg_1_1 => grp_TOP_Pipeline_2_fu_130_outreg_1_1,
        outreg_1_1_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_1_1_ap_vld,
        outreg_1 => grp_TOP_Pipeline_2_fu_130_outreg_1,
        outreg_1_ap_vld => grp_TOP_Pipeline_2_fu_130_outreg_1_ap_vld);

    grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150 : component TOP_TOP_Pipeline_VITIS_LOOP_177_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_start,
        ap_done => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_done,
        ap_idle => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_idle,
        ap_ready => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_ready,
        IN_r_TVALID => IN_r_TVALID_int_regslice,
        OUT_r_TREADY => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_OUT_r_TREADY,
        IN_r_TDATA => IN_r_TDATA_int_regslice,
        IN_r_TREADY => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_IN_r_TREADY,
        OUT_r_TDATA => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_OUT_r_TDATA,
        OUT_r_TVALID => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_OUT_r_TVALID,
        inreg_0_1_i => inreg_0_1_fu_50,
        inreg_0_1_o => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_1_o,
        inreg_0_1_o_ap_vld => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_1_o_ap_vld,
        inreg_0_i => inreg_0_fu_42,
        inreg_0_o => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_o,
        inreg_0_o_ap_vld => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_o_ap_vld,
        inreg_1_i => inreg_1_fu_46,
        inreg_1_o => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_o,
        inreg_1_o_ap_vld => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_o_ap_vld,
        inreg_1_1_i => inreg_1_1_fu_54,
        inreg_1_1_o => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_1_o,
        inreg_1_1_o_ap_vld => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_1_o_ap_vld,
        outreg_0_i => outreg_0_fu_58,
        outreg_0_o => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_0_o,
        outreg_0_o_ap_vld => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_0_o_ap_vld,
        outreg_1_i => outreg_1_fu_62,
        outreg_1_o => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_1_o,
        outreg_1_o_ap_vld => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_1_o_ap_vld,
        outreg_0_1 => outreg_0_1_fu_66,
        outreg_1_1 => outreg_1_1_fu_70,
        outreg_0_2 => outreg_0_2_fu_74,
        outreg_1_2 => outreg_1_2_fu_78,
        outreg_0_3 => outreg_0_3_fu_82,
        outreg_1_3 => outreg_1_3_fu_86,
        outreg_0_4 => outreg_0_4_fu_90,
        outreg_1_4 => outreg_1_4_fu_94,
        outreg_0_5 => outreg_0_5_fu_98,
        outreg_1_5 => outreg_1_5_fu_102,
        outreg_0_6 => outreg_0_6_fu_106,
        outreg_1_6 => outreg_1_6_fu_110,
        outreg_0_7 => outreg_0_7_fu_114,
        outreg_1_7 => outreg_1_7_fu_118);

    regslice_both_IN_r_V_data_V_U : component TOP_regslice_both
    generic map (
        DataWidth => 192)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN_r_TDATA,
        vld_in => IN_r_TVALID,
        ack_in => regslice_both_IN_r_V_data_V_U_ack_in,
        data_out => IN_r_TDATA_int_regslice,
        vld_out => IN_r_TVALID_int_regslice,
        ack_out => IN_r_TREADY_int_regslice,
        apdone_blk => regslice_both_IN_r_V_data_V_U_apdone_blk);

    regslice_both_OUT_r_V_data_V_U : component TOP_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_OUT_r_TDATA,
        vld_in => grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_OUT_r_TVALID,
        ack_in => OUT_r_TREADY_int_regslice,
        data_out => OUT_r_TDATA,
        vld_out => regslice_both_OUT_r_V_data_V_U_vld_out,
        ack_out => OUT_r_TREADY,
        apdone_blk => regslice_both_OUT_r_V_data_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_TOP_Pipeline_1_fu_122_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_TOP_Pipeline_1_fu_122_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_TOP_Pipeline_1_fu_122_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_TOP_Pipeline_1_fu_122_ap_ready = ap_const_logic_1)) then 
                    grp_TOP_Pipeline_1_fu_122_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_TOP_Pipeline_2_fu_130_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_TOP_Pipeline_2_fu_130_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_TOP_Pipeline_2_fu_130_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_TOP_Pipeline_2_fu_130_ap_ready = ap_const_logic_1)) then 
                    grp_TOP_Pipeline_2_fu_130_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_ready = ap_const_logic_1)) then 
                    grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    inreg_0_1_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_1_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                inreg_0_1_fu_50 <= grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_1_o;
            elsif (((grp_TOP_Pipeline_1_fu_122_inreg_0_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                inreg_0_1_fu_50 <= grp_TOP_Pipeline_1_fu_122_inreg_0_1;
            end if; 
        end if;
    end process;

    inreg_0_fu_42_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_o_ap_vld = ap_const_logic_1))) then 
                inreg_0_fu_42 <= grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_0_o;
            elsif (((grp_TOP_Pipeline_1_fu_122_inreg_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                inreg_0_fu_42 <= grp_TOP_Pipeline_1_fu_122_inreg_0;
            end if; 
        end if;
    end process;

    inreg_1_1_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_1_o_ap_vld = ap_const_logic_1))) then 
                inreg_1_1_fu_54 <= grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_1_o;
            elsif (((grp_TOP_Pipeline_1_fu_122_inreg_1_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                inreg_1_1_fu_54 <= grp_TOP_Pipeline_1_fu_122_inreg_1_1;
            end if; 
        end if;
    end process;

    inreg_1_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_o_ap_vld = ap_const_logic_1))) then 
                inreg_1_fu_46 <= grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_inreg_1_o;
            elsif (((grp_TOP_Pipeline_1_fu_122_inreg_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                inreg_1_fu_46 <= grp_TOP_Pipeline_1_fu_122_inreg_1;
            end if; 
        end if;
    end process;

    outreg_0_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_0_o_ap_vld = ap_const_logic_1))) then 
                outreg_0_fu_58 <= grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_0_o;
            elsif (((grp_TOP_Pipeline_2_fu_130_outreg_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                outreg_0_fu_58 <= grp_TOP_Pipeline_2_fu_130_outreg_0;
            end if; 
        end if;
    end process;

    outreg_1_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_1_o_ap_vld = ap_const_logic_1))) then 
                outreg_1_fu_62 <= grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_outreg_1_o;
            elsif (((grp_TOP_Pipeline_2_fu_130_outreg_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                outreg_1_fu_62 <= grp_TOP_Pipeline_2_fu_130_outreg_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_0_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_0_1_fu_66 <= grp_TOP_Pipeline_2_fu_130_outreg_0_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_0_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_0_2_fu_74 <= grp_TOP_Pipeline_2_fu_130_outreg_0_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_0_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_0_3_fu_82 <= grp_TOP_Pipeline_2_fu_130_outreg_0_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_0_4_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_0_4_fu_90 <= grp_TOP_Pipeline_2_fu_130_outreg_0_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_0_5_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_0_5_fu_98 <= grp_TOP_Pipeline_2_fu_130_outreg_0_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_0_6_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_0_6_fu_106 <= grp_TOP_Pipeline_2_fu_130_outreg_0_6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_0_7_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_0_7_fu_114 <= grp_TOP_Pipeline_2_fu_130_outreg_0_7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_1_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_1_1_fu_70 <= grp_TOP_Pipeline_2_fu_130_outreg_1_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_1_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_1_2_fu_78 <= grp_TOP_Pipeline_2_fu_130_outreg_1_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_1_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_1_3_fu_86 <= grp_TOP_Pipeline_2_fu_130_outreg_1_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_1_4_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_1_4_fu_94 <= grp_TOP_Pipeline_2_fu_130_outreg_1_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_1_5_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_1_5_fu_102 <= grp_TOP_Pipeline_2_fu_130_outreg_1_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_1_6_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_1_6_fu_110 <= grp_TOP_Pipeline_2_fu_130_outreg_1_6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_TOP_Pipeline_2_fu_130_outreg_1_7_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                outreg_1_7_fu_118 <= grp_TOP_Pipeline_2_fu_130_outreg_1_7;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state5, regslice_both_OUT_r_V_data_V_U_apdone_blk, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((regslice_both_OUT_r_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    IN_r_TREADY <= regslice_both_IN_r_V_data_V_U_ack_in;

    IN_r_TREADY_int_regslice_assign_proc : process(grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_IN_r_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            IN_r_TREADY_int_regslice <= grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_IN_r_TREADY;
        else 
            IN_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    OUT_r_TVALID <= regslice_both_OUT_r_V_data_V_U_vld_out;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_done)
    begin
        if ((grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(regslice_both_OUT_r_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_OUT_r_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_TOP_Pipeline_1_fu_122_ap_done, grp_TOP_Pipeline_2_fu_130_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_TOP_Pipeline_2_fu_130_ap_done = ap_const_logic_0) or (grp_TOP_Pipeline_1_fu_122_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5, regslice_both_OUT_r_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_OUT_r_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, regslice_both_OUT_r_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_OUT_r_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_TOP_Pipeline_1_fu_122_ap_start <= grp_TOP_Pipeline_1_fu_122_ap_start_reg;
    grp_TOP_Pipeline_2_fu_130_ap_start <= grp_TOP_Pipeline_2_fu_130_ap_start_reg;
    grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_OUT_r_TREADY <= (ap_CS_fsm_state4 and OUT_r_TREADY_int_regslice);
    grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_start <= grp_TOP_Pipeline_VITIS_LOOP_177_1_fu_150_ap_start_reg;
end behav;
