// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="TOP_TOP,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.049000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2651,HLS_SYN_LUT=6729,HLS_VERSION=2023_2}" *)

module TOP (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        IN_r_TVALID,
        OUT_r_TREADY,
        IN_r_TDATA,
        IN_r_TREADY,
        OUT_r_TDATA,
        OUT_r_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   IN_r_TVALID;
input   OUT_r_TREADY;
input  [191:0] IN_r_TDATA;
output   IN_r_TREADY;
output  [127:0] OUT_r_TDATA;
output   OUT_r_TVALID;

reg ap_idle;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    regslice_both_OUT_r_V_data_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln110_fu_1257_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    IN_r_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    OUT_r_TDATA_blk_n;
reg   [4:0] tmp_reg_2886;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] tmp_3_reg_2891;
reg   [0:0] tmp_1_reg_2897;
wire   [3:0] tmp_6_fu_851_p4;
reg   [3:0] tmp_6_reg_2925;
wire   [6:0] trunc_ln26_fu_861_p1;
reg   [6:0] trunc_ln26_reg_2929;
wire   [0:0] tmp_2_fu_865_p3;
reg   [0:0] tmp_2_reg_2933;
reg   [63:0] ap_phi_mux_out_data_4_phi_fu_370_p30;
wire   [63:0] grp_fu_729_p19;
reg   [63:0] ap_phi_reg_pp0_iter1_out_data_4_reg_365;
wire   [63:0] ap_phi_reg_pp0_iter0_out_data_4_reg_365;
wire   [63:0] out_data_2_fu_2444_p19;
reg   [63:0] inreg_0_0_fu_192;
wire   [63:0] grp_fu_571_p3;
reg   [63:0] inreg_12_0_fu_196;
wire   [63:0] grp_fu_565_p3;
reg   [63:0] inreg_1_0_0_fu_200;
wire   [63:0] grp_fu_583_p3;
reg   [63:0] inreg_1_1_0_fu_204;
wire   [63:0] grp_fu_577_p3;
reg   [63:0] inreg_2_0_0_fu_208;
wire   [63:0] grp_fu_535_p3;
reg   [63:0] inreg_2_1_0_fu_212;
wire   [63:0] grp_fu_529_p3;
reg   [63:0] inreg_3_0_0_fu_216;
wire   [63:0] grp_fu_547_p3;
reg   [63:0] inreg_3_1_0_fu_220;
wire   [63:0] grp_fu_541_p3;
reg   [63:0] inreg_4_0_0_fu_224;
wire   [63:0] grp_fu_499_p3;
reg   [63:0] inreg_4_1_0_fu_228;
wire   [63:0] grp_fu_493_p3;
reg   [63:0] inreg_5_0_0_fu_232;
wire   [63:0] grp_fu_511_p3;
reg   [63:0] inreg_5_1_0_fu_236;
wire   [63:0] grp_fu_505_p3;
reg   [63:0] inreg_6_0_0_fu_240;
wire   [63:0] grp_fu_463_p3;
reg   [63:0] inreg_6_1_0_fu_244;
wire   [63:0] grp_fu_457_p3;
reg   [63:0] inreg_7_0_0_fu_248;
wire   [63:0] grp_fu_475_p3;
reg   [63:0] inreg_7_1_0_fu_252;
wire   [63:0] grp_fu_469_p3;
reg   [63:0] inreg_8_0_0_fu_256;
wire   [63:0] grp_fu_427_p3;
reg   [63:0] inreg_8_1_0_fu_260;
wire   [63:0] grp_fu_421_p3;
reg   [63:0] inreg_9_0_0_fu_264;
wire   [63:0] grp_fu_439_p3;
reg   [63:0] inreg_9_1_0_fu_268;
wire   [63:0] grp_fu_433_p3;
reg   [63:0] inreg_10_0_0_fu_272;
wire   [63:0] grp_fu_607_p3;
reg   [63:0] inreg_10_1_0_fu_276;
wire   [63:0] grp_fu_601_p3;
reg   [63:0] inreg_11_0_0_fu_280;
wire   [63:0] grp_fu_619_p3;
reg   [63:0] inreg_11_1_0_fu_284;
wire   [63:0] grp_fu_613_p3;
reg   [63:0] outreg_0_0_fu_288;
wire   [63:0] outreg_1_42_fu_2328_p3;
reg   [63:0] outreg_1279_0_fu_292;
wire   [63:0] outreg_1_41_fu_2321_p3;
reg   [63:0] outreg_1_0_0435_fu_296;
wire   [63:0] outreg_1_40_fu_2314_p3;
reg   [63:0] outreg_1_1_0436_fu_300;
wire   [63:0] outreg_1_39_fu_2307_p3;
reg   [63:0] outreg_2_0_0437_fu_304;
wire   [63:0] outreg_1_38_fu_2300_p3;
reg   [63:0] outreg_2_1_0438_fu_308;
wire   [63:0] outreg_1_37_fu_2293_p3;
reg   [63:0] outreg_3_0_0439_fu_312;
wire   [63:0] outreg_1_36_fu_2286_p3;
reg   [63:0] outreg_3_1_0440_fu_316;
wire   [63:0] outreg_1_35_fu_2279_p3;
reg   [63:0] outreg_4_0_0441_fu_320;
wire   [63:0] outreg_1_34_fu_2272_p3;
reg   [63:0] outreg_4_1_0442_fu_324;
wire   [63:0] outreg_1_33_fu_2265_p3;
reg   [63:0] outreg_5_0_0443_fu_328;
wire   [63:0] outreg_1_32_fu_2258_p3;
reg   [63:0] outreg_5_1_0444_fu_332;
wire   [63:0] outreg_1_31_fu_2251_p3;
reg   [63:0] outreg_6_0_0445_fu_336;
wire   [63:0] outreg_1_30_fu_2244_p3;
reg   [63:0] outreg_6_1_0446_fu_340;
wire   [63:0] outreg_1_29_fu_2237_p3;
reg   [63:0] outreg_7_0_0447_fu_344;
wire   [63:0] outreg_1_28_fu_2230_p3;
reg   [63:0] outreg_7_1_0448_fu_348;
wire   [63:0] outreg_1_27_fu_2223_p3;
reg    ap_block_pp0_stage0_01001;
wire   [63:0] in_rs1_fu_779_p4;
wire   [63:0] in_rs2_fu_801_p4;
wire   [63:0] grp_fu_729_p2;
wire   [63:0] grp_fu_729_p4;
wire   [63:0] grp_fu_729_p6;
wire   [63:0] grp_fu_729_p8;
wire   [63:0] grp_fu_729_p10;
wire   [63:0] grp_fu_729_p12;
wire   [63:0] grp_fu_729_p14;
wire   [63:0] grp_fu_729_p16;
wire   [63:0] grp_fu_729_p17;
wire   [63:0] in_inst_fu_775_p1;
wire   [63:0] s1_fu_1335_p3;
wire   [63:0] s2_fu_1346_p3;
wire   [7:0] c1_fu_1357_p1;
wire   [7:0] c2_fu_1361_p1;
wire   [7:0] c1_1_fu_1371_p4;
wire   [7:0] c2_1_fu_1381_p4;
wire   [7:0] c1_2_fu_1397_p4;
wire   [7:0] c2_2_fu_1407_p4;
wire   [7:0] c1_3_fu_1423_p4;
wire   [7:0] c2_3_fu_1433_p4;
wire   [7:0] c1_4_fu_1449_p4;
wire   [7:0] c2_4_fu_1459_p4;
wire   [7:0] c1_5_fu_1475_p4;
wire   [7:0] c2_5_fu_1485_p4;
wire   [7:0] c1_6_fu_1501_p4;
wire   [7:0] c2_6_fu_1511_p4;
wire   [7:0] c1_7_fu_1527_p4;
wire   [7:0] c2_7_fu_1537_p4;
wire   [0:0] icmp_ln15_1_fu_1391_p2;
wire   [0:0] icmp_ln15_4_fu_1469_p2;
wire   [0:0] icmp_ln15_3_fu_1443_p2;
wire   [1:0] select_ln16_1_fu_1561_p3;
wire   [15:0] select_ln13_fu_1569_p3;
wire   [15:0] select_ln16_fu_1553_p3;
wire   [33:0] or_ln16_2_fu_1577_p4;
wire   [0:0] icmp_ln15_6_fu_1521_p2;
wire   [9:0] select_ln16_2_fu_1591_p3;
wire  signed [39:0] sext_ln16_fu_1587_p1;
wire   [49:0] tmp2_fu_1599_p3;
wire   [0:0] icmp_ln15_5_fu_1495_p2;
wire   [0:0] icmp_ln15_fu_1365_p2;
wire   [0:0] icmp_ln15_7_fu_1547_p2;
wire   [0:0] icmp_ln15_2_fu_1417_p2;
wire   [17:0] select_ln16_3_fu_1611_p3;
wire   [15:0] select_ln13_1_fu_1635_p3;
wire   [7:0] select_ln16_4_fu_1619_p3;
wire   [41:0] or_ln16_5_fu_1643_p4;
wire   [49:0] select_ln16_5_fu_1627_p3;
wire   [7:0] tmp_4_fu_1657_p4;
wire  signed [47:0] sext_ln16_2_fu_1653_p1;
wire   [55:0] tmp_7_fu_1667_p3;
wire  signed [55:0] sext_ln16_1_fu_1607_p1;
wire   [1:0] tmp_9_fu_1681_p4;
wire   [55:0] or_ln16_fu_1675_p2;
wire  signed [57:0] result_fu_1691_p3;
wire  signed [63:0] sext_ln9_fu_1699_p1;
wire   [31:0] trunc_ln26_1_fu_1717_p1;
wire   [31:0] trunc_ln26_2_fu_1721_p1;
wire   [31:0] up_fu_1353_p1;
wire   [31:0] diag_fu_1342_p1;
wire   [0:0] icmp_ln31_fu_1732_p2;
wire   [31:0] left_fu_1725_p3;
wire   [31:0] max_val_2_fu_1738_p3;
wire   [0:0] icmp_ln32_fu_1746_p2;
wire   [0:0] xor_ln32_fu_1760_p2;
wire   [0:0] or_ln32_fu_1770_p2;
wire   [1:0] zext_ln32_fu_1766_p1;
wire  signed [31:0] max_val_fu_1752_p3;
wire   [1:0] dir_fu_1776_p3;
wire   [31:0] trunc_ln24_fu_1796_p1;
wire   [31:0] trunc_ln24_1_fu_1800_p1;
wire   [31:0] trunc_ln25_fu_1811_p1;
wire   [31:0] trunc_ln25_1_fu_1815_p1;
wire   [31:0] up_4_fu_1819_p3;
wire   [31:0] diag_1_fu_1804_p3;
wire   [0:0] icmp_ln31_1_fu_1826_p2;
wire   [31:0] trunc_ln26_3_fu_1840_p1;
wire   [31:0] trunc_ln26_4_fu_1844_p1;
wire   [31:0] left_1_fu_1848_p3;
wire   [31:0] max_val_16_fu_1832_p3;
wire   [0:0] icmp_ln32_1_fu_1855_p2;
wire   [0:0] xor_ln32_1_fu_1869_p2;
wire   [0:0] or_ln32_1_fu_1879_p2;
wire   [1:0] zext_ln32_1_fu_1875_p1;
wire   [31:0] max_val_17_fu_1861_p3;
wire   [1:0] dir_4_fu_1885_p3;
wire   [31:0] trunc_ln24_2_fu_1901_p1;
wire   [31:0] trunc_ln24_3_fu_1905_p1;
wire   [31:0] trunc_ln25_2_fu_1916_p1;
wire   [31:0] trunc_ln25_3_fu_1920_p1;
wire   [31:0] up_5_fu_1924_p3;
wire   [31:0] diag_2_fu_1909_p3;
wire   [0:0] icmp_ln31_2_fu_1931_p2;
wire   [31:0] trunc_ln26_5_fu_1945_p1;
wire   [31:0] trunc_ln26_6_fu_1949_p1;
wire   [31:0] left_2_fu_1953_p3;
wire   [31:0] max_val_18_fu_1937_p3;
wire   [0:0] icmp_ln32_2_fu_1960_p2;
wire   [0:0] xor_ln32_2_fu_1974_p2;
wire   [0:0] or_ln32_2_fu_1984_p2;
wire   [1:0] zext_ln32_2_fu_1980_p1;
wire   [31:0] max_val_19_fu_1966_p3;
wire   [1:0] dir_5_fu_1990_p3;
wire   [31:0] trunc_ln24_4_fu_2006_p1;
wire   [31:0] trunc_ln24_5_fu_2010_p1;
wire   [31:0] trunc_ln25_4_fu_2021_p1;
wire   [31:0] trunc_ln25_5_fu_2025_p1;
wire   [31:0] trunc_ln26_7_fu_2036_p1;
wire   [31:0] trunc_ln26_8_fu_2040_p1;
wire   [31:0] up_6_fu_2029_p3;
wire   [31:0] diag_3_fu_2014_p3;
wire   [0:0] icmp_ln31_3_fu_2051_p2;
wire   [31:0] left_3_fu_2044_p3;
wire   [31:0] max_val_13_fu_2057_p3;
wire   [0:0] icmp_ln32_3_fu_2065_p2;
wire   [0:0] xor_ln32_3_fu_2079_p2;
wire   [0:0] or_ln32_3_fu_2089_p2;
wire   [1:0] zext_ln32_3_fu_2085_p1;
wire   [31:0] max_val_20_fu_2071_p3;
wire   [1:0] dir_6_fu_2095_p3;
wire  signed [63:0] sext_ln34_fu_1784_p1;
wire   [63:0] zext_ln35_fu_1792_p1;
wire  signed [63:0] sext_ln34_1_fu_1893_p1;
wire   [63:0] zext_ln35_1_fu_1897_p1;
wire  signed [63:0] sext_ln34_2_fu_1998_p1;
wire   [63:0] zext_ln35_2_fu_2002_p1;
wire  signed [63:0] sext_ln34_3_fu_2103_p1;
wire   [63:0] zext_ln35_3_fu_2107_p1;
wire   [63:0] outreg_1_25_fu_2209_p3;
wire   [63:0] outreg_1_26_fu_2216_p3;
wire   [63:0] outreg_1_22_fu_2195_p3;
wire   [63:0] outreg_1_23_fu_2202_p3;
wire   [63:0] outreg_1_19_fu_2181_p3;
wire   [63:0] outreg_1_20_fu_2188_p3;
wire   [63:0] outreg_1_16_fu_2167_p3;
wire   [63:0] outreg_1_17_fu_2174_p3;
wire   [63:0] outreg_1_13_fu_2153_p3;
wire   [63:0] outreg_1_14_fu_2160_p3;
wire   [63:0] outreg_1_10_fu_2139_p3;
wire   [63:0] outreg_1_11_fu_2146_p3;
wire   [63:0] outreg_1_7_fu_2125_p3;
wire   [63:0] outreg_1_8_fu_2132_p3;
wire   [63:0] outreg_1_4_fu_2111_p3;
wire   [63:0] outreg_1_1_fu_1703_p3;
wire   [63:0] outreg_1_5_fu_2118_p3;
wire   [63:0] outreg_1_2_fu_1710_p3;
wire  signed [57:0] sext_ln35_fu_1788_p1;
wire   [57:0] outreg_1_43_fu_2335_p3;
wire   [63:0] select_ln88_14_fu_2346_p3;
wire   [63:0] select_ln88_15_fu_2360_p3;
wire   [63:0] select_ln88_16_fu_2374_p3;
wire   [63:0] select_ln88_17_fu_2388_p3;
wire   [63:0] select_ln88_18_fu_2402_p3;
wire   [63:0] select_ln88_19_fu_2416_p3;
wire   [63:0] select_ln88_20_fu_2430_p3;
wire  signed [63:0] out_data_2_fu_2444_p2;
wire   [63:0] out_data_2_fu_2444_p4;
wire   [63:0] out_data_2_fu_2444_p6;
wire   [63:0] out_data_2_fu_2444_p8;
wire   [63:0] out_data_2_fu_2444_p10;
wire   [63:0] out_data_2_fu_2444_p12;
wire   [63:0] out_data_2_fu_2444_p14;
wire   [63:0] out_data_2_fu_2444_p16;
wire   [63:0] out_data_2_fu_2444_p17;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_loop_init;
wire    regslice_both_IN_r_V_data_V_U_apdone_blk;
wire   [191:0] IN_r_TDATA_int_regslice;
wire    IN_r_TVALID_int_regslice;
reg    IN_r_TREADY_int_regslice;
wire    regslice_both_IN_r_V_data_V_U_ack_in;
wire   [127:0] OUT_r_TDATA_int_regslice;
reg    OUT_r_TVALID_int_regslice;
wire    OUT_r_TREADY_int_regslice;
wire    regslice_both_OUT_r_V_data_V_U_vld_out;
wire   [2:0] grp_fu_729_p1;
wire   [2:0] grp_fu_729_p3;
wire   [2:0] grp_fu_729_p5;
wire   [2:0] grp_fu_729_p7;
wire  signed [2:0] grp_fu_729_p9;
wire  signed [2:0] grp_fu_729_p11;
wire  signed [2:0] grp_fu_729_p13;
wire  signed [2:0] grp_fu_729_p15;
wire   [2:0] out_data_2_fu_2444_p1;
wire   [2:0] out_data_2_fu_2444_p3;
wire   [2:0] out_data_2_fu_2444_p5;
wire   [2:0] out_data_2_fu_2444_p7;
wire  signed [2:0] out_data_2_fu_2444_p9;
wire  signed [2:0] out_data_2_fu_2444_p11;
wire  signed [2:0] out_data_2_fu_2444_p13;
wire  signed [2:0] out_data_2_fu_2444_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
   ap_CS_fsm = 1'd1;
   ap_enable_reg_pp0_iter1 = 1'b0;
   ap_enable_reg_pp0_iter2 = 1'b0;
   inreg_0_0_fu_192 = 64'd0;
   inreg_12_0_fu_196 = 64'd0;
   inreg_1_0_0_fu_200 = 64'd0;
   inreg_1_1_0_fu_204 = 64'd0;
   inreg_2_0_0_fu_208 = 64'd0;
   inreg_2_1_0_fu_212 = 64'd0;
   inreg_3_0_0_fu_216 = 64'd0;
   inreg_3_1_0_fu_220 = 64'd0;
   inreg_4_0_0_fu_224 = 64'd0;
   inreg_4_1_0_fu_228 = 64'd0;
   inreg_5_0_0_fu_232 = 64'd0;
   inreg_5_1_0_fu_236 = 64'd0;
   inreg_6_0_0_fu_240 = 64'd0;
   inreg_6_1_0_fu_244 = 64'd0;
   inreg_7_0_0_fu_248 = 64'd0;
   inreg_7_1_0_fu_252 = 64'd0;
   inreg_8_0_0_fu_256 = 64'd0;
   inreg_8_1_0_fu_260 = 64'd0;
   inreg_9_0_0_fu_264 = 64'd0;
   inreg_9_1_0_fu_268 = 64'd0;
   inreg_10_0_0_fu_272 = 64'd0;
   inreg_10_1_0_fu_276 = 64'd0;
   inreg_11_0_0_fu_280 = 64'd0;
   inreg_11_1_0_fu_284 = 64'd0;
   outreg_0_0_fu_288 = 64'd0;
   outreg_1279_0_fu_292 = 64'd0;
   outreg_1_0_0435_fu_296 = 64'd0;
   outreg_1_1_0436_fu_300 = 64'd0;
   outreg_2_0_0437_fu_304 = 64'd0;
   outreg_2_1_0438_fu_308 = 64'd0;
   outreg_3_0_0439_fu_312 = 64'd0;
   outreg_3_1_0440_fu_316 = 64'd0;
   outreg_4_0_0441_fu_320 = 64'd0;
   outreg_4_1_0442_fu_324 = 64'd0;
   outreg_5_0_0443_fu_328 = 64'd0;
   outreg_5_1_0444_fu_332 = 64'd0;
   outreg_6_0_0445_fu_336 = 64'd0;
   outreg_6_1_0446_fu_340 = 64'd0;
   outreg_7_0_0447_fu_344 = 64'd0;
   outreg_7_1_0448_fu_348 = 64'd0;
   ap_done_reg = 1'b0;
end

TOP_sparsemux_17_3_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 64 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 64 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 64 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 64 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
sparsemux_17_3_64_1_1_U1(
    .din0(grp_fu_729_p2),
    .din1(grp_fu_729_p4),
    .din2(grp_fu_729_p6),
    .din3(grp_fu_729_p8),
    .din4(grp_fu_729_p10),
    .din5(grp_fu_729_p12),
    .din6(grp_fu_729_p14),
    .din7(grp_fu_729_p16),
    .def(grp_fu_729_p17),
    .sel(tmp_3_reg_2891),
    .dout(grp_fu_729_p19)
);

TOP_sparsemux_17_3_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 64 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 64 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 64 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 64 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
sparsemux_17_3_64_1_1_U2(
    .din0(out_data_2_fu_2444_p2),
    .din1(out_data_2_fu_2444_p4),
    .din2(out_data_2_fu_2444_p6),
    .din3(out_data_2_fu_2444_p8),
    .din4(out_data_2_fu_2444_p10),
    .din5(out_data_2_fu_2444_p12),
    .din6(out_data_2_fu_2444_p14),
    .din7(out_data_2_fu_2444_p16),
    .def(out_data_2_fu_2444_p17),
    .sel(tmp_3_reg_2891),
    .dout(out_data_2_fu_2444_p19)
);

TOP_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

TOP_regslice_both #(
    .DataWidth( 192 ))
regslice_both_IN_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN_r_TDATA),
    .vld_in(IN_r_TVALID),
    .ack_in(regslice_both_IN_r_V_data_V_U_ack_in),
    .data_out(IN_r_TDATA_int_regslice),
    .vld_out(IN_r_TVALID_int_regslice),
    .ack_out(IN_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_IN_r_V_data_V_U_apdone_blk)
);

TOP_regslice_both #(
    .DataWidth( 128 ))
regslice_both_OUT_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(OUT_r_TDATA_int_regslice),
    .vld_in(OUT_r_TVALID_int_regslice),
    .ack_in(OUT_r_TREADY_int_regslice),
    .data_out(OUT_r_TDATA),
    .vld_out(regslice_both_OUT_r_V_data_V_U_vld_out),
    .ack_out(OUT_r_TREADY),
    .apdone_blk(regslice_both_OUT_r_V_data_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd11) & (tmp_6_fu_851_p4 == 4'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd11) & (tmp_6_fu_851_p4 == 4'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd11) & (tmp_6_fu_851_p4 == 4'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd11) & (tmp_6_fu_851_p4 == 4'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd11) & (tmp_6_fu_851_p4 == 4'd0)) | (~(tmp_6_fu_851_p4 == 4'd4) & ~(tmp_6_fu_851_p4 == 4'd3) & ~(tmp_6_fu_851_p4 == 4'd2) & ~(tmp_6_fu_851_p4 == 4'd1) & ~(tmp_6_fu_851_p4 == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) 
    & (trunc_ln26_fu_861_p1 == 7'd11)))) begin
        ap_phi_reg_pp0_iter1_out_data_4_reg_365 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_out_data_4_reg_365 <= ap_phi_reg_pp0_iter0_out_data_4_reg_365;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        tmp_1_reg_2897 <= IN_r_TDATA_int_regslice[32'd30];
        tmp_2_reg_2933 <= IN_r_TDATA_int_regslice[32'd31];
        tmp_3_reg_2891 <= {{IN_r_TDATA_int_regslice[14:12]}};
        tmp_6_reg_2925 <= {{IN_r_TDATA_int_regslice[29:26]}};
        tmp_reg_2886 <= {{IN_r_TDATA_int_regslice[11:7]}};
        trunc_ln26_reg_2929 <= trunc_ln26_fu_861_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd91) & (tmp_6_fu_851_p4 == 4'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd123) & (tmp_6_fu_851_p4 == 4'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd11) & (tmp_6_fu_851_p4 == 4'd0)))) begin
        inreg_0_0_fu_192 <= grp_fu_571_p3;
        inreg_12_0_fu_196 <= grp_fu_565_p3;
        inreg_1_0_0_fu_200 <= grp_fu_583_p3;
        inreg_1_1_0_fu_204 <= grp_fu_577_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((~(tmp_6_fu_851_p4 == 4'd4) & ~(tmp_6_fu_851_p4 == 4'd3) & ~(tmp_6_fu_851_p4 == 4'd2) & ~(tmp_6_fu_851_p4 == 4'd1) & ~(tmp_6_fu_851_p4 == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd91)) | (~(tmp_6_fu_851_p4 == 4'd4) & ~(tmp_6_fu_851_p4 == 4'd3) & ~(tmp_6_fu_851_p4 == 4'd2) & ~(tmp_6_fu_851_p4 == 4'd1) & ~(tmp_6_fu_851_p4 == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd123)) | (~(tmp_6_fu_851_p4 == 4'd4) & ~(tmp_6_fu_851_p4 == 4'd3) & ~(tmp_6_fu_851_p4 == 4'd2) & ~(tmp_6_fu_851_p4 == 4'd1) & ~(tmp_6_fu_851_p4 == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd11)))) begin
        inreg_10_0_0_fu_272 <= grp_fu_607_p3;
        inreg_10_1_0_fu_276 <= grp_fu_601_p3;
        inreg_11_0_0_fu_280 <= grp_fu_619_p3;
        inreg_11_1_0_fu_284 <= grp_fu_613_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd91) & (tmp_6_fu_851_p4 == 4'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd123) & (tmp_6_fu_851_p4 == 4'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd11) & (tmp_6_fu_851_p4 == 4'd1)))) begin
        inreg_2_0_0_fu_208 <= grp_fu_535_p3;
        inreg_2_1_0_fu_212 <= grp_fu_529_p3;
        inreg_3_0_0_fu_216 <= grp_fu_547_p3;
        inreg_3_1_0_fu_220 <= grp_fu_541_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd91) & (tmp_6_fu_851_p4 == 4'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd123) & (tmp_6_fu_851_p4 == 4'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd11) & (tmp_6_fu_851_p4 == 4'd2)))) begin
        inreg_4_0_0_fu_224 <= grp_fu_499_p3;
        inreg_4_1_0_fu_228 <= grp_fu_493_p3;
        inreg_5_0_0_fu_232 <= grp_fu_511_p3;
        inreg_5_1_0_fu_236 <= grp_fu_505_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd91) & (tmp_6_fu_851_p4 == 4'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd123) & (tmp_6_fu_851_p4 == 4'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd11) & (tmp_6_fu_851_p4 == 4'd3)))) begin
        inreg_6_0_0_fu_240 <= grp_fu_463_p3;
        inreg_6_1_0_fu_244 <= grp_fu_457_p3;
        inreg_7_0_0_fu_248 <= grp_fu_475_p3;
        inreg_7_1_0_fu_252 <= grp_fu_469_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd91) & (tmp_6_fu_851_p4 == 4'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd123) & (tmp_6_fu_851_p4 == 4'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_fu_861_p1 == 7'd11) & (tmp_6_fu_851_p4 == 4'd4)))) begin
        inreg_8_0_0_fu_256 <= grp_fu_427_p3;
        inreg_8_1_0_fu_260 <= grp_fu_421_p3;
        inreg_9_0_0_fu_264 <= grp_fu_439_p3;
        inreg_9_1_0_fu_268 <= grp_fu_433_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln26_reg_2929 == 7'd123))) begin
        outreg_0_0_fu_288 <= outreg_1_42_fu_2328_p3;
        outreg_1279_0_fu_292 <= outreg_1_41_fu_2321_p3;
        outreg_1_0_0435_fu_296 <= outreg_1_40_fu_2314_p3;
        outreg_1_1_0436_fu_300 <= outreg_1_39_fu_2307_p3;
        outreg_2_0_0437_fu_304 <= outreg_1_38_fu_2300_p3;
        outreg_2_1_0438_fu_308 <= outreg_1_37_fu_2293_p3;
        outreg_3_0_0439_fu_312 <= outreg_1_36_fu_2286_p3;
        outreg_3_1_0440_fu_316 <= outreg_1_35_fu_2279_p3;
        outreg_4_0_0441_fu_320 <= outreg_1_34_fu_2272_p3;
        outreg_4_1_0442_fu_324 <= outreg_1_33_fu_2265_p3;
        outreg_5_0_0443_fu_328 <= outreg_1_32_fu_2258_p3;
        outreg_5_1_0444_fu_332 <= outreg_1_31_fu_2251_p3;
        outreg_6_0_0445_fu_336 <= outreg_1_30_fu_2244_p3;
        outreg_6_1_0446_fu_340 <= outreg_1_29_fu_2237_p3;
        outreg_7_0_0447_fu_344 <= outreg_1_28_fu_2230_p3;
        outreg_7_1_0448_fu_348 <= outreg_1_27_fu_2223_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        IN_r_TDATA_blk_n = IN_r_TVALID_int_regslice;
    end else begin
        IN_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        IN_r_TREADY_int_regslice = 1'b1;
    end else begin
        IN_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        OUT_r_TDATA_blk_n = OUT_r_TREADY_int_regslice;
    end else begin
        OUT_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OUT_r_TVALID_int_regslice = 1'b1;
    end else begin
        OUT_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln110_fu_1257_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((trunc_ln26_reg_2929 == 7'd123)) begin
        ap_phi_mux_out_data_4_phi_fu_370_p30 = out_data_2_fu_2444_p19;
    end else if (((trunc_ln26_reg_2929 == 7'd43) | (~(tmp_6_reg_2925 == 4'd4) & ~(tmp_6_reg_2925 == 4'd3) & ~(tmp_6_reg_2925 == 4'd2) & ~(tmp_6_reg_2925 == 4'd1) & ~(tmp_6_reg_2925 == 4'd0) & (trunc_ln26_reg_2929 == 7'd91)) | ((trunc_ln26_reg_2929 == 7'd91) & (tmp_6_reg_2925 == 4'd4)) | ((trunc_ln26_reg_2929 == 7'd91) & (tmp_6_reg_2925 == 4'd3)) | ((trunc_ln26_reg_2929 == 7'd91) & (tmp_6_reg_2925 == 4'd2)) | ((trunc_ln26_reg_2929 == 7'd91) & (tmp_6_reg_2925 == 4'd1)) | ((trunc_ln26_reg_2929 == 7'd91) & (tmp_6_reg_2925 == 4'd0)))) begin
        ap_phi_mux_out_data_4_phi_fu_370_p30 = grp_fu_729_p19;
    end else begin
        ap_phi_mux_out_data_4_phi_fu_370_p30 = ap_phi_reg_pp0_iter1_out_data_4_reg_365;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign IN_r_TREADY = regslice_both_IN_r_V_data_V_U_ack_in;

assign OUT_r_TDATA_int_regslice = {{{ap_phi_mux_out_data_4_phi_fu_370_p30}, {59'd0}}, {tmp_reg_2886}};

assign OUT_r_TVALID = regslice_both_OUT_r_V_data_V_U_vld_out;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_OUT_r_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_OUT_r_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b0 == OUT_r_TREADY_int_regslice) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == OUT_r_TREADY_int_regslice) | (1'b1 == ap_block_state2_pp0_stage0_iter1))) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_OUT_r_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b0 == OUT_r_TREADY_int_regslice) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == OUT_r_TREADY_int_regslice) | (1'b1 == ap_block_state2_pp0_stage0_iter1))) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (1'b0 == IN_r_TVALID_int_regslice);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (1'b0 == OUT_r_TREADY_int_regslice);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_OUT_r_V_data_V_U_apdone_blk == 1'b1) | (1'b0 == OUT_r_TREADY_int_regslice));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_out_data_4_reg_365 = 'bx;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign c1_1_fu_1371_p4 = {{s1_fu_1335_p3[15:8]}};

assign c1_2_fu_1397_p4 = {{s1_fu_1335_p3[23:16]}};

assign c1_3_fu_1423_p4 = {{s1_fu_1335_p3[31:24]}};

assign c1_4_fu_1449_p4 = {{s1_fu_1335_p3[39:32]}};

assign c1_5_fu_1475_p4 = {{s1_fu_1335_p3[47:40]}};

assign c1_6_fu_1501_p4 = {{s1_fu_1335_p3[55:48]}};

assign c1_7_fu_1527_p4 = {{s1_fu_1335_p3[63:56]}};

assign c1_fu_1357_p1 = s1_fu_1335_p3[7:0];

assign c2_1_fu_1381_p4 = {{s2_fu_1346_p3[15:8]}};

assign c2_2_fu_1407_p4 = {{s2_fu_1346_p3[23:16]}};

assign c2_3_fu_1433_p4 = {{s2_fu_1346_p3[31:24]}};

assign c2_4_fu_1459_p4 = {{s2_fu_1346_p3[39:32]}};

assign c2_5_fu_1485_p4 = {{s2_fu_1346_p3[47:40]}};

assign c2_6_fu_1511_p4 = {{s2_fu_1346_p3[55:48]}};

assign c2_7_fu_1537_p4 = {{s2_fu_1346_p3[63:56]}};

assign c2_fu_1361_p1 = s2_fu_1346_p3[7:0];

assign diag_1_fu_1804_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? trunc_ln24_fu_1796_p1 : trunc_ln24_1_fu_1800_p1);

assign diag_2_fu_1909_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? trunc_ln24_2_fu_1901_p1 : trunc_ln24_3_fu_1905_p1);

assign diag_3_fu_2014_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? trunc_ln24_4_fu_2006_p1 : trunc_ln24_5_fu_2010_p1);

assign diag_fu_1342_p1 = s1_fu_1335_p3[31:0];

assign dir_4_fu_1885_p3 = ((or_ln32_1_fu_1879_p2[0:0] == 1'b1) ? zext_ln32_1_fu_1875_p1 : 2'd2);

assign dir_5_fu_1990_p3 = ((or_ln32_2_fu_1984_p2[0:0] == 1'b1) ? zext_ln32_2_fu_1980_p1 : 2'd2);

assign dir_6_fu_2095_p3 = ((or_ln32_3_fu_2089_p2[0:0] == 1'b1) ? zext_ln32_3_fu_2085_p1 : 2'd2);

assign dir_fu_1776_p3 = ((or_ln32_fu_1770_p2[0:0] == 1'b1) ? zext_ln32_fu_1766_p1 : 2'd2);

assign grp_fu_421_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs1_fu_779_p4 : inreg_8_1_0_fu_260);

assign grp_fu_427_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_8_0_0_fu_256 : in_rs1_fu_779_p4);

assign grp_fu_433_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs2_fu_801_p4 : inreg_9_1_0_fu_268);

assign grp_fu_439_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_9_0_0_fu_264 : in_rs2_fu_801_p4);

assign grp_fu_457_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs1_fu_779_p4 : inreg_6_1_0_fu_244);

assign grp_fu_463_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_6_0_0_fu_240 : in_rs1_fu_779_p4);

assign grp_fu_469_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs2_fu_801_p4 : inreg_7_1_0_fu_252);

assign grp_fu_475_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_7_0_0_fu_248 : in_rs2_fu_801_p4);

assign grp_fu_493_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs1_fu_779_p4 : inreg_4_1_0_fu_228);

assign grp_fu_499_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_4_0_0_fu_224 : in_rs1_fu_779_p4);

assign grp_fu_505_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs2_fu_801_p4 : inreg_5_1_0_fu_236);

assign grp_fu_511_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_5_0_0_fu_232 : in_rs2_fu_801_p4);

assign grp_fu_529_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs1_fu_779_p4 : inreg_2_1_0_fu_212);

assign grp_fu_535_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_2_0_0_fu_208 : in_rs1_fu_779_p4);

assign grp_fu_541_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs2_fu_801_p4 : inreg_3_1_0_fu_220);

assign grp_fu_547_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_3_0_0_fu_216 : in_rs2_fu_801_p4);

assign grp_fu_565_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs1_fu_779_p4 : inreg_12_0_fu_196);

assign grp_fu_571_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_0_0_fu_192 : in_rs1_fu_779_p4);

assign grp_fu_577_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs2_fu_801_p4 : inreg_1_1_0_fu_204);

assign grp_fu_583_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_1_0_0_fu_200 : in_rs2_fu_801_p4);

assign grp_fu_601_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs1_fu_779_p4 : inreg_10_1_0_fu_276);

assign grp_fu_607_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_10_0_0_fu_272 : in_rs1_fu_779_p4);

assign grp_fu_613_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? in_rs2_fu_801_p4 : inreg_11_1_0_fu_284);

assign grp_fu_619_p3 = ((tmp_2_fu_865_p3[0:0] == 1'b1) ? inreg_11_0_0_fu_280 : in_rs2_fu_801_p4);

assign grp_fu_729_p10 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_4_1_0442_fu_324 : outreg_4_0_0441_fu_320);

assign grp_fu_729_p12 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_5_1_0444_fu_332 : outreg_5_0_0443_fu_328);

assign grp_fu_729_p14 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_6_1_0446_fu_340 : outreg_6_0_0445_fu_336);

assign grp_fu_729_p16 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_7_1_0448_fu_348 : outreg_7_0_0447_fu_344);

assign grp_fu_729_p17 = 'bx;

assign grp_fu_729_p2 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_1279_0_fu_292 : outreg_0_0_fu_288);

assign grp_fu_729_p4 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_1_1_0436_fu_300 : outreg_1_0_0435_fu_296);

assign grp_fu_729_p6 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_2_1_0438_fu_308 : outreg_2_0_0437_fu_304);

assign grp_fu_729_p8 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_3_1_0440_fu_316 : outreg_3_0_0439_fu_312);

assign icmp_ln110_fu_1257_p2 = ((in_inst_fu_775_p1 == 64'd0) ? 1'b1 : 1'b0);

assign icmp_ln15_1_fu_1391_p2 = ((c1_1_fu_1371_p4 == c2_1_fu_1381_p4) ? 1'b1 : 1'b0);

assign icmp_ln15_2_fu_1417_p2 = ((c1_2_fu_1397_p4 == c2_2_fu_1407_p4) ? 1'b1 : 1'b0);

assign icmp_ln15_3_fu_1443_p2 = ((c1_3_fu_1423_p4 == c2_3_fu_1433_p4) ? 1'b1 : 1'b0);

assign icmp_ln15_4_fu_1469_p2 = ((c1_4_fu_1449_p4 == c2_4_fu_1459_p4) ? 1'b1 : 1'b0);

assign icmp_ln15_5_fu_1495_p2 = ((c1_5_fu_1475_p4 == c2_5_fu_1485_p4) ? 1'b1 : 1'b0);

assign icmp_ln15_6_fu_1521_p2 = ((c1_6_fu_1501_p4 == c2_6_fu_1511_p4) ? 1'b1 : 1'b0);

assign icmp_ln15_7_fu_1547_p2 = ((c1_7_fu_1527_p4 == c2_7_fu_1537_p4) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_1365_p2 = ((c1_fu_1357_p1 == c2_fu_1361_p1) ? 1'b1 : 1'b0);

assign icmp_ln31_1_fu_1826_p2 = (($signed(up_4_fu_1819_p3) > $signed(diag_1_fu_1804_p3)) ? 1'b1 : 1'b0);

assign icmp_ln31_2_fu_1931_p2 = (($signed(up_5_fu_1924_p3) > $signed(diag_2_fu_1909_p3)) ? 1'b1 : 1'b0);

assign icmp_ln31_3_fu_2051_p2 = (($signed(up_6_fu_2029_p3) > $signed(diag_3_fu_2014_p3)) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_1732_p2 = (($signed(up_fu_1353_p1) > $signed(diag_fu_1342_p1)) ? 1'b1 : 1'b0);

assign icmp_ln32_1_fu_1855_p2 = (($signed(left_1_fu_1848_p3) > $signed(max_val_16_fu_1832_p3)) ? 1'b1 : 1'b0);

assign icmp_ln32_2_fu_1960_p2 = (($signed(left_2_fu_1953_p3) > $signed(max_val_18_fu_1937_p3)) ? 1'b1 : 1'b0);

assign icmp_ln32_3_fu_2065_p2 = (($signed(left_3_fu_2044_p3) > $signed(max_val_13_fu_2057_p3)) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_1746_p2 = (($signed(left_fu_1725_p3) > $signed(max_val_2_fu_1738_p3)) ? 1'b1 : 1'b0);

assign in_inst_fu_775_p1 = IN_r_TDATA_int_regslice[63:0];

assign in_rs1_fu_779_p4 = {{IN_r_TDATA_int_regslice[127:64]}};

assign in_rs2_fu_801_p4 = {{IN_r_TDATA_int_regslice[191:128]}};

assign left_1_fu_1848_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? trunc_ln26_3_fu_1840_p1 : trunc_ln26_4_fu_1844_p1);

assign left_2_fu_1953_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? trunc_ln26_5_fu_1945_p1 : trunc_ln26_6_fu_1949_p1);

assign left_3_fu_2044_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? trunc_ln26_7_fu_2036_p1 : trunc_ln26_8_fu_2040_p1);

assign left_fu_1725_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? trunc_ln26_1_fu_1717_p1 : trunc_ln26_2_fu_1721_p1);

assign max_val_13_fu_2057_p3 = ((icmp_ln31_3_fu_2051_p2[0:0] == 1'b1) ? up_6_fu_2029_p3 : diag_3_fu_2014_p3);

assign max_val_16_fu_1832_p3 = ((icmp_ln31_1_fu_1826_p2[0:0] == 1'b1) ? up_4_fu_1819_p3 : diag_1_fu_1804_p3);

assign max_val_17_fu_1861_p3 = ((icmp_ln32_1_fu_1855_p2[0:0] == 1'b1) ? left_1_fu_1848_p3 : max_val_16_fu_1832_p3);

assign max_val_18_fu_1937_p3 = ((icmp_ln31_2_fu_1931_p2[0:0] == 1'b1) ? up_5_fu_1924_p3 : diag_2_fu_1909_p3);

assign max_val_19_fu_1966_p3 = ((icmp_ln32_2_fu_1960_p2[0:0] == 1'b1) ? left_2_fu_1953_p3 : max_val_18_fu_1937_p3);

assign max_val_20_fu_2071_p3 = ((icmp_ln32_3_fu_2065_p2[0:0] == 1'b1) ? left_3_fu_2044_p3 : max_val_13_fu_2057_p3);

assign max_val_2_fu_1738_p3 = ((icmp_ln31_fu_1732_p2[0:0] == 1'b1) ? up_fu_1353_p1 : diag_fu_1342_p1);

assign max_val_fu_1752_p3 = ((icmp_ln32_fu_1746_p2[0:0] == 1'b1) ? left_fu_1725_p3 : max_val_2_fu_1738_p3);

assign or_ln16_2_fu_1577_p4 = {{{select_ln16_1_fu_1561_p3}, {select_ln13_fu_1569_p3}}, {select_ln16_fu_1553_p3}};

assign or_ln16_5_fu_1643_p4 = {{{select_ln16_3_fu_1611_p3}, {select_ln13_1_fu_1635_p3}}, {select_ln16_4_fu_1619_p3}};

assign or_ln16_fu_1675_p2 = (tmp_7_fu_1667_p3 | sext_ln16_1_fu_1607_p1);

assign or_ln32_1_fu_1879_p2 = (icmp_ln32_1_fu_1855_p2 | icmp_ln31_1_fu_1826_p2);

assign or_ln32_2_fu_1984_p2 = (icmp_ln32_2_fu_1960_p2 | icmp_ln31_2_fu_1931_p2);

assign or_ln32_3_fu_2089_p2 = (icmp_ln32_3_fu_2065_p2 | icmp_ln31_3_fu_2051_p2);

assign or_ln32_fu_1770_p2 = (icmp_ln32_fu_1746_p2 | icmp_ln31_fu_1732_p2);

assign out_data_2_fu_2444_p10 = ((tmp_1_reg_2897[0:0] == 1'b1) ? sext_ln34_2_fu_1998_p1 : select_ln88_17_fu_2388_p3);

assign out_data_2_fu_2444_p12 = ((tmp_1_reg_2897[0:0] == 1'b1) ? zext_ln35_2_fu_2002_p1 : select_ln88_18_fu_2402_p3);

assign out_data_2_fu_2444_p14 = ((tmp_1_reg_2897[0:0] == 1'b1) ? sext_ln34_3_fu_2103_p1 : select_ln88_19_fu_2416_p3);

assign out_data_2_fu_2444_p16 = ((tmp_1_reg_2897[0:0] == 1'b1) ? zext_ln35_3_fu_2107_p1 : select_ln88_20_fu_2430_p3);

assign out_data_2_fu_2444_p17 = 'bx;

assign out_data_2_fu_2444_p2 = $signed(outreg_1_43_fu_2335_p3);

assign out_data_2_fu_2444_p4 = ((tmp_1_reg_2897[0:0] == 1'b1) ? zext_ln35_fu_1792_p1 : select_ln88_14_fu_2346_p3);

assign out_data_2_fu_2444_p6 = ((tmp_1_reg_2897[0:0] == 1'b1) ? sext_ln34_1_fu_1893_p1 : select_ln88_15_fu_2360_p3);

assign out_data_2_fu_2444_p8 = ((tmp_1_reg_2897[0:0] == 1'b1) ? zext_ln35_1_fu_1897_p1 : select_ln88_16_fu_2374_p3);

assign outreg_1_10_fu_2139_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? sext_ln34_1_fu_1893_p1 : outreg_2_1_0438_fu_308);

assign outreg_1_11_fu_2146_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_2_0_0437_fu_304 : sext_ln34_1_fu_1893_p1);

assign outreg_1_13_fu_2153_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? zext_ln35_1_fu_1897_p1 : outreg_3_1_0440_fu_316);

assign outreg_1_14_fu_2160_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_3_0_0439_fu_312 : zext_ln35_1_fu_1897_p1);

assign outreg_1_16_fu_2167_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? sext_ln34_2_fu_1998_p1 : outreg_4_1_0442_fu_324);

assign outreg_1_17_fu_2174_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_4_0_0441_fu_320 : sext_ln34_2_fu_1998_p1);

assign outreg_1_19_fu_2181_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? zext_ln35_2_fu_2002_p1 : outreg_5_1_0444_fu_332);

assign outreg_1_1_fu_1703_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? sext_ln9_fu_1699_p1 : outreg_1279_0_fu_292);

assign outreg_1_20_fu_2188_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_5_0_0443_fu_328 : zext_ln35_2_fu_2002_p1);

assign outreg_1_22_fu_2195_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? sext_ln34_3_fu_2103_p1 : outreg_6_1_0446_fu_340);

assign outreg_1_23_fu_2202_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_6_0_0445_fu_336 : sext_ln34_3_fu_2103_p1);

assign outreg_1_25_fu_2209_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? zext_ln35_3_fu_2107_p1 : outreg_7_1_0448_fu_348);

assign outreg_1_26_fu_2216_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_7_0_0447_fu_344 : zext_ln35_3_fu_2107_p1);

assign outreg_1_27_fu_2223_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_25_fu_2209_p3 : outreg_7_1_0448_fu_348);

assign outreg_1_28_fu_2230_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_26_fu_2216_p3 : outreg_7_0_0447_fu_344);

assign outreg_1_29_fu_2237_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_22_fu_2195_p3 : outreg_6_1_0446_fu_340);

assign outreg_1_2_fu_1710_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_0_0_fu_288 : sext_ln9_fu_1699_p1);

assign outreg_1_30_fu_2244_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_23_fu_2202_p3 : outreg_6_0_0445_fu_336);

assign outreg_1_31_fu_2251_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_19_fu_2181_p3 : outreg_5_1_0444_fu_332);

assign outreg_1_32_fu_2258_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_20_fu_2188_p3 : outreg_5_0_0443_fu_328);

assign outreg_1_33_fu_2265_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_16_fu_2167_p3 : outreg_4_1_0442_fu_324);

assign outreg_1_34_fu_2272_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_17_fu_2174_p3 : outreg_4_0_0441_fu_320);

assign outreg_1_35_fu_2279_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_13_fu_2153_p3 : outreg_3_1_0440_fu_316);

assign outreg_1_36_fu_2286_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_14_fu_2160_p3 : outreg_3_0_0439_fu_312);

assign outreg_1_37_fu_2293_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_10_fu_2139_p3 : outreg_2_1_0438_fu_308);

assign outreg_1_38_fu_2300_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_11_fu_2146_p3 : outreg_2_0_0437_fu_304);

assign outreg_1_39_fu_2307_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_7_fu_2125_p3 : outreg_1_1_0436_fu_300);

assign outreg_1_40_fu_2314_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_8_fu_2132_p3 : outreg_1_0_0435_fu_296);

assign outreg_1_41_fu_2321_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_4_fu_2111_p3 : outreg_1_1_fu_1703_p3);

assign outreg_1_42_fu_2328_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? outreg_1_5_fu_2118_p3 : outreg_1_2_fu_1710_p3);

assign outreg_1_43_fu_2335_p3 = ((tmp_1_reg_2897[0:0] == 1'b1) ? sext_ln35_fu_1788_p1 : result_fu_1691_p3);

assign outreg_1_4_fu_2111_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? sext_ln34_fu_1784_p1 : outreg_1279_0_fu_292);

assign outreg_1_5_fu_2118_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_0_0_fu_288 : sext_ln34_fu_1784_p1);

assign outreg_1_7_fu_2125_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? zext_ln35_fu_1792_p1 : outreg_1_1_0436_fu_300);

assign outreg_1_8_fu_2132_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_1_0_0435_fu_296 : zext_ln35_fu_1792_p1);

assign result_fu_1691_p3 = {{tmp_9_fu_1681_p4}, {or_ln16_fu_1675_p2}};

assign s1_fu_1335_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? inreg_12_0_fu_196 : inreg_0_0_fu_192);

assign s2_fu_1346_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? inreg_1_1_0_fu_204 : inreg_1_0_0_fu_200);

assign select_ln13_1_fu_1635_p3 = ((icmp_ln15_2_fu_1417_p2[0:0] == 1'b1) ? 16'd256 : 16'd65280);

assign select_ln13_fu_1569_p3 = ((icmp_ln15_3_fu_1443_p2[0:0] == 1'b1) ? 16'd256 : 16'd65280);

assign select_ln16_1_fu_1561_p3 = ((icmp_ln15_4_fu_1469_p2[0:0] == 1'b1) ? 2'd1 : 2'd3);

assign select_ln16_2_fu_1591_p3 = ((icmp_ln15_6_fu_1521_p2[0:0] == 1'b1) ? 10'd256 : 10'd768);

assign select_ln16_3_fu_1611_p3 = ((icmp_ln15_5_fu_1495_p2[0:0] == 1'b1) ? 18'd65536 : 18'd196608);

assign select_ln16_4_fu_1619_p3 = ((icmp_ln15_fu_1365_p2[0:0] == 1'b1) ? 8'd1 : 8'd255);

assign select_ln16_5_fu_1627_p3 = ((icmp_ln15_7_fu_1547_p2[0:0] == 1'b1) ? 50'd281474976710656 : 50'd844424930131968);

assign select_ln16_fu_1553_p3 = ((icmp_ln15_1_fu_1391_p2[0:0] == 1'b1) ? 16'd256 : 16'd65280);

assign select_ln88_14_fu_2346_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_1_1_0436_fu_300 : outreg_1_0_0435_fu_296);

assign select_ln88_15_fu_2360_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_2_1_0438_fu_308 : outreg_2_0_0437_fu_304);

assign select_ln88_16_fu_2374_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_3_1_0440_fu_316 : outreg_3_0_0439_fu_312);

assign select_ln88_17_fu_2388_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_4_1_0442_fu_324 : outreg_4_0_0441_fu_320);

assign select_ln88_18_fu_2402_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_5_1_0444_fu_332 : outreg_5_0_0443_fu_328);

assign select_ln88_19_fu_2416_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_6_1_0446_fu_340 : outreg_6_0_0445_fu_336);

assign select_ln88_20_fu_2430_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? outreg_7_1_0448_fu_348 : outreg_7_0_0447_fu_344);

assign sext_ln16_1_fu_1607_p1 = $signed(tmp2_fu_1599_p3);

assign sext_ln16_2_fu_1653_p1 = $signed(or_ln16_5_fu_1643_p4);

assign sext_ln16_fu_1587_p1 = $signed(or_ln16_2_fu_1577_p4);

assign sext_ln34_1_fu_1893_p1 = $signed(max_val_17_fu_1861_p3);

assign sext_ln34_2_fu_1998_p1 = $signed(max_val_19_fu_1966_p3);

assign sext_ln34_3_fu_2103_p1 = $signed(max_val_20_fu_2071_p3);

assign sext_ln34_fu_1784_p1 = max_val_fu_1752_p3;

assign sext_ln35_fu_1788_p1 = max_val_fu_1752_p3;

assign sext_ln9_fu_1699_p1 = result_fu_1691_p3;

assign tmp2_fu_1599_p3 = {{select_ln16_2_fu_1591_p3}, {sext_ln16_fu_1587_p1}};

assign tmp_2_fu_865_p3 = IN_r_TDATA_int_regslice[32'd31];

assign tmp_4_fu_1657_p4 = {{select_ln16_5_fu_1627_p3[47:40]}};

assign tmp_6_fu_851_p4 = {{IN_r_TDATA_int_regslice[29:26]}};

assign tmp_7_fu_1667_p3 = {{tmp_4_fu_1657_p4}, {sext_ln16_2_fu_1653_p1}};

assign tmp_9_fu_1681_p4 = {{select_ln16_5_fu_1627_p3[49:48]}};

assign trunc_ln24_1_fu_1800_p1 = inreg_3_0_0_fu_216[31:0];

assign trunc_ln24_2_fu_1901_p1 = inreg_6_1_0_fu_244[31:0];

assign trunc_ln24_3_fu_1905_p1 = inreg_6_0_0_fu_240[31:0];

assign trunc_ln24_4_fu_2006_p1 = inreg_9_1_0_fu_268[31:0];

assign trunc_ln24_5_fu_2010_p1 = inreg_9_0_0_fu_264[31:0];

assign trunc_ln24_fu_1796_p1 = inreg_3_1_0_fu_220[31:0];

assign trunc_ln25_1_fu_1815_p1 = inreg_4_0_0_fu_224[31:0];

assign trunc_ln25_2_fu_1916_p1 = inreg_7_1_0_fu_252[31:0];

assign trunc_ln25_3_fu_1920_p1 = inreg_7_0_0_fu_248[31:0];

assign trunc_ln25_4_fu_2021_p1 = inreg_10_1_0_fu_276[31:0];

assign trunc_ln25_5_fu_2025_p1 = inreg_10_0_0_fu_272[31:0];

assign trunc_ln25_fu_1811_p1 = inreg_4_1_0_fu_228[31:0];

assign trunc_ln26_1_fu_1717_p1 = inreg_2_1_0_fu_212[31:0];

assign trunc_ln26_2_fu_1721_p1 = inreg_2_0_0_fu_208[31:0];

assign trunc_ln26_3_fu_1840_p1 = inreg_5_1_0_fu_236[31:0];

assign trunc_ln26_4_fu_1844_p1 = inreg_5_0_0_fu_232[31:0];

assign trunc_ln26_5_fu_1945_p1 = inreg_8_1_0_fu_260[31:0];

assign trunc_ln26_6_fu_1949_p1 = inreg_8_0_0_fu_256[31:0];

assign trunc_ln26_7_fu_2036_p1 = inreg_11_1_0_fu_284[31:0];

assign trunc_ln26_8_fu_2040_p1 = inreg_11_0_0_fu_280[31:0];

assign trunc_ln26_fu_861_p1 = IN_r_TDATA_int_regslice[6:0];

assign up_4_fu_1819_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? trunc_ln25_fu_1811_p1 : trunc_ln25_1_fu_1815_p1);

assign up_5_fu_1924_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? trunc_ln25_2_fu_1916_p1 : trunc_ln25_3_fu_1920_p1);

assign up_6_fu_2029_p3 = ((tmp_2_reg_2933[0:0] == 1'b1) ? trunc_ln25_4_fu_2021_p1 : trunc_ln25_5_fu_2025_p1);

assign up_fu_1353_p1 = s2_fu_1346_p3[31:0];

assign xor_ln32_1_fu_1869_p2 = (icmp_ln32_1_fu_1855_p2 ^ 1'd1);

assign xor_ln32_2_fu_1974_p2 = (icmp_ln32_2_fu_1960_p2 ^ 1'd1);

assign xor_ln32_3_fu_2079_p2 = (icmp_ln32_3_fu_2065_p2 ^ 1'd1);

assign xor_ln32_fu_1760_p2 = (icmp_ln32_fu_1746_p2 ^ 1'd1);

assign zext_ln32_1_fu_1875_p1 = xor_ln32_1_fu_1869_p2;

assign zext_ln32_2_fu_1980_p1 = xor_ln32_2_fu_1974_p2;

assign zext_ln32_3_fu_2085_p1 = xor_ln32_3_fu_2079_p2;

assign zext_ln32_fu_1766_p1 = xor_ln32_fu_1760_p2;

assign zext_ln35_1_fu_1897_p1 = dir_4_fu_1885_p3;

assign zext_ln35_2_fu_2002_p1 = dir_5_fu_1990_p3;

assign zext_ln35_3_fu_2107_p1 = dir_6_fu_2095_p3;

assign zext_ln35_fu_1792_p1 = dir_fu_1776_p3;


reg find_kernel_block = 0;
// synthesis translate_off
`include "TOP_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //TOP

